In [2]:
import pandas as pd
import numpy as np
import sklearn

In [3]:
data = pd.read_csv('../../1_datasets/processed_data/store_01.csv', index_col='Date', parse_dates=True)
data.head(20)

,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
Date,,,,,,,,,,,,,
2022-01-01,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
2022-01-01,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2022-01-01,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
2022-01-01,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
2022-01-01,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer
2022-01-01,P0006,Groceries,South,138,128,102,139.82,76.83,10,Sunny,1,79.35,Winter
2022-01-01,P0007,Furniture,East,359,97,167,108.92,34.16,10,Rainy,1,36.55,Winter
2022-01-01,P0008,Clothing,North,380,312,54,329.73,97.99,5,Cloudy,0,100.09,Spring
2022-01-01,P0009,Electronics,West,183,175,135,174.15,20.74,10,Cloudy,0,17.66,Autumn
2022-01-01,P0010,Toys,South,108,28,196,24.47,59.99,0,Rainy,1,61.21,Winter
2022-01-01,P0011,Furniture,South,258,150,153,152.74,58.53,10,Sunny,1,61.42,Spring
2022-01-01,P0012,Clothing,West,66,24,70,26.75,58.25,20,Snowy,0,62.21,Spring
2022-01-01,P0013,Toys,South,96,42,85,41.46,43.60,0,Cloudy,0,46.31,Spring
2022-01-01,P0014,Clothing,West,193,12,187,6.80,78.11,0,Sunny,0,80.06,Spring
2022-01-01,P0015,Clothing,North,379,369,154,363.46,92.99,15,Snowy,0,95.80,Winter
2022-01-01,P0016,Electronics,North,363,255,69,255.74,21.90,5,Cloudy,1,20.27,Autumn
2022-01-01,P0017,Toys,West,318,246,177,255.37,21.07,20,Sunny,0,16.49,Winter
2022-01-01,P0018,Clothing,South,241,151,47,147.27,19.57,5,Cloudy,0,23.13,Autumn
2022-01-01,P0019,Clothing,East,352,257,186,267.38,73.28,10,Cloudy,0,77.26,Winter
2022-01-01,P0020,Toys,East,274,99,166,115.23,30.24,5,Cloudy,0,27.10,Spring

In [9]:
## ETS Decomposition

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt


# get error trend seasonality (ETS) for time series

result = seasonal_decompose(data['Units Sold'], model='multiplicative')
result.plot()

ValueError: Multiplicative seasonality is not appropriate for zero and negative values

In [22]:
from sklearn.model_selection import train_test_split

x = data["Date"]
y = data.drop(columns=["Date"],axis=1,inplace=False)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1) # 70 : 30 split

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

data = x_train,y_train